// components/googleapidocs/constants/endpoints.ts
import { Endpoint } from '../components/types';

export const endpoints: Endpoint[] = [
  {
    id: 'get-customers',
    method: 'GET',
    path: '/api/customers',
    title: 'List Customers',
    description: 'Retrieve paginated customers list',
    category: 'customers',
    requiresAuth: true,
    parameters: [
      { name: 'page', type: 'number', required: false, description: 'Page number' },
      { name: 'limit', type: 'number', required: false, description: 'Items per page' },
      { name: 'search', type: 'string', required: false, description: 'Search customers' },
    ],
    exampleRequest: `GET /api/customers?page=1&limit=20\nAuthorization: Bearer YOUR_TOKEN`,
    exampleResponse: `{\n  "success": true,\n  "data": {\n    "customers": [...],\n    "pagination": {...}\n  }\n}`,
  },
  {
    id: 'create-customer',
    method: 'POST',
    path: '/api/customers',
    title: 'Create Customer',
    description: 'Add new customer to system',
    category: 'customers',
    requiresAuth: true,
    parameters: [
      { name: 'name', type: 'string', required: true, description: 'Customer name' },
      { name: 'email', type: 'string', required: true, description: 'Customer email' },
      { name: 'phone', type: 'string', required: false, description: 'Phone number' },
    ],
    exampleRequest: `POST /api/customers\nAuthorization: Bearer YOUR_TOKEN\nContent-Type: application/json\n\n{\n  "name": "John Doe",\n  "email": "john@example.com"\n}`,
    exampleResponse: `{\n  "success": true,\n  "data": {\n    "customer": {\n      "id": "123",\n      "name": "John Doe",\n      "email": "john@example.com"\n    }\n  }\n}`,
  },
  {
    id: 'get-products',
    method: 'GET',
    path: '/api/products',
    title: 'List Products',
    description: 'Get all products with inventory',
    category: 'products',
    requiresAuth: true,
    parameters: [
      { name: 'category', type: 'string', required: false, description: 'Filter category' },
      { name: 'inStock', type: 'boolean', required: false, description: 'In stock only' },
    ],
    exampleRequest: `GET /api/products?category=electronics\nAuthorization: Bearer YOUR_TOKEN`,
    exampleResponse: `{\n  "success": true,\n  "data": {\n    "products": [\n      {\n        "id": "p123",\n        "name": "Laptop",\n        "price": 999.99,\n        "stock": 15\n      }\n    ]\n  }\n}`,
  },
  {
    id: 'update-product',
    method: 'PUT',
    path: '/api/products/{id}',
    title: 'Update Product',
    description: 'Update product details',
    category: 'products',
    requiresAuth: true,
    parameters: [
      { name: 'name', type: 'string', required: false, description: 'Product name' },
      { name: 'price', type: 'number', required: false, description: 'Product price' },
      { name: 'stock', type: 'number', required: false, description: 'Stock quantity' },
    ],
    exampleRequest: `PUT /api/products/p123\nAuthorization: Bearer YOUR_TOKEN\nContent-Type: application/json\n\n{\n  "price": 899.99,\n  "stock": 20\n}`,
    exampleResponse: `{\n  "success": true,\n  "data": {\n    "product": {\n      "id": "p123",\n      "name": "Laptop",\n      "price": 899.99,\n      "stock": 20\n    }\n  }\n}`,
  },
  {
    id: 'get-invoices',
    method: 'GET',
    path: '/api/invoices',
    title: 'List Invoices',
    description: 'Retrieve invoices with filters',
    category: 'invoices',
    requiresAuth: true,
    parameters: [
      { name: 'status', type: 'string', required: false, description: 'Status filter' },
      { name: 'customerId', type: 'string', required: false, description: 'Customer filter' },
    ],
    exampleRequest: `GET /api/invoices?status=paid\nAuthorization: Bearer YOUR_TOKEN`,
    exampleResponse: `{\n  "success": true,\n  "data": {\n    "invoices": [\n      {\n        "id": "inv123",\n        "total": 999.99,\n        "status": "paid"\n      }\n    ]\n  }\n}`,
  },
  {
    id: 'create-invoice',
    method: 'POST',
    path: '/api/invoices',
    title: 'Create Invoice',
    description: 'Generate new invoice',
    category: 'invoices',
    requiresAuth: true,
    parameters: [
      { name: 'customerId', type: 'string', required: true, description: 'Customer ID' },
      { name: 'items', type: 'array', required: true, description: 'Invoice items' },
    ],
    exampleRequest: `POST /api/invoices\nAuthorization: Bearer YOUR_TOKEN\nContent-Type: application/json\n\n{\n  "customerId": "cust123",\n  "items": [\n    {\n      "productId": "p123",\n      "quantity": 1,\n      "price": 999.99\n    }\n  ]\n}`,
    exampleResponse: `{\n  "success": true,\n  "data": {\n    "invoice": {\n      "id": "inv456",\n      "invoiceNumber": "INV-2024-001",\n      "total": 999.99\n    }\n  }\n}`,
  },
  {
    id: 'get-analytics',
    method: 'GET',
    path: '/api/analytics',
    title: 'Get Analytics',
    description: 'Retrieve business analytics',
    category: 'analytics',
    requiresAuth: true,
    parameters: [
      { name: 'period', type: 'string', required: false, description: 'Time period' },
      { name: 'startDate', type: 'string', required: false, description: 'Start date' },
    ],
    exampleRequest: `GET /api/analytics?period=monthly\nAuthorization: Bearer YOUR_TOKEN`,
    exampleResponse: `{\n  "success": true,\n  "data": {\n    "revenue": 15000,\n    "totalSales": 120,\n    "topProducts": [...]\n  }\n}`,
  },
];

export const categories = [
  { value: 'all', label: 'All APIs' },
  { value: 'customers', label: 'Customers' },
  { value: 'products', label: 'Products' },
  { value: 'invoices', label: 'Invoices' },
  { value: 'analytics', label: 'Analytics' },
];